# Generated by Django 5.2.1 on 2025-06-02 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_host', models.CharField(max_length=100, unique=True, verbose_name='Nome do Host/Etiqueta')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Observações')),
                ('setor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor/Departamento')),
                ('pos_x', models.IntegerField(default=0, verbose_name='Posição X no Layout')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Posição Y no Layout')),
                ('status_reportado', models.CharField(choices=[('ok', 'OK'), ('problema', 'Com Problema'), ('manutencao', 'Em Manutenção')], default='ok', max_length=20, verbose_name='Status Reportado')),
                ('status_rede', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('erro_ip', 'IP Incorreto'), ('nao_verificado', 'Não Verificado')], default='nao_verificado', max_length=20, verbose_name='Status da Rede (Ping)')),
                ('ultimo_ping_status', models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação de Ping')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(unique=True, verbose_name='Endereço IP')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Endereço IP',
                'verbose_name_plural': 'Endereços IP',
            },
        ),
        migrations.CreateModel(
            name='ChamadoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Problema')),
                ('descricao_problema', models.TextField(verbose_name='Descrição Detalhada')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('status_chamado', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('aguardando_peca', 'Aguardando Peça'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status do Chamado')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('solucao_aplicada', models.TextField(blank=True, null=True, verbose_name='Solução Aplicada')),
                ('aberto_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Aberto Por')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.computador', verbose_name='Computador')),
            ],
            options={
                'verbose_name': 'Chamado de Manutenção',
                'verbose_name_plural': 'Chamados de Manutenção',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.AddField(
            model_name='computador',
            name='ip_associado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ipaddress', verbose_name='IP Associado'),
        ),
    ]
